export const coverageExclude = [
  '**/coverage/*',
  '**/mocks/*',
  '**/index.ts',
  '**/*-model.ts',
  '**/*-config.ts',
  '**/bootstrap.ts',
  '**/*-routes.ts',
  '**/*-const.ts',
  '**/*.config.ts',
  '**/*.config.cjs',
  '**/scripts/*',
  '**/*.html',
  '**/*.css',
];
