import type { FastifyInstance } from 'fastify';
import { register as registerAccessTokens } from './access-tokens-api';
import { register as registerAddWatchedItem } from './add-movie-tracker-item-api';
import { register as registerAddWatchingItem } from './add-series-tracker-item-api';
import { register as registerModify } from './change-api';
import { register as registerUpdateTagManagement } from './update-tag-management-api';
import { register as registerRenameTagManagement } from './rename-tag-management-api';
import { register as registerChangeToken } from './change-token-api';
import { register as registerChangeUserSettings } from './change-user-settings-api';
import { register as registerCollectionItemsExists } from './collection-items-exists-api';
import { register as registerCollectionItemsMatched } from './collection-items-matched-api';
import { register as registerCollectionItemsSearchSuggestions } from './collection-items-search-suggestions-api';
import { register as registerChangeWatchingSeasons } from './change-series-tracker-seasons-api';
import { register as registerChangeWatchingWatchedEpisodes } from './change-series-tracker-watched-episodes-api';
import { register as registerMarkAllWatchingWatched } from './mark-all-series-tracker-watched-api';
import { register as registerMarkAllSeriesUnwatched } from './mark-all-series-unwatched-api';
import { register as registerMarkAllSeriesWatched } from './mark-all-series-watched-api';
import { register as registerCreateAccessToken } from './create-access-token-api';
import { register as registerCreate } from './create-api';
import { register as registerDeleteAccessToken } from './delete-access-token-api';
import { register as registerDeleteBooksItems } from './delete-book-tracker-items-api';
import { register as registerDelete } from './delete-api';
import { register as registerDeleteIncomingUserShare } from './delete-incoming-user-share-api';
import { register as registerDeleteWatchedItem } from './delete-movie-tracker-item-api';
import { register as registerDeleteWatchedItems } from './delete-movie-tracker-items-api';
import { register as registerDeleteWatchingItems } from './delete-series-tracker-items-api';
import { register as registerDeleteWatchingSeasons } from './delete-series-tracker-seasons-api';
import { register as registerDeleteUser } from './delete-user-api';
import { register as registerDeleteUserShare } from './delete-user-share-api';
import { register as registerGenreSuggestions } from './genre-suggestions-api';
import { register as registerGetCollectionItems } from './get-collection-items-api';
import { register as registerGetWatchingSeasons } from './get-series-tracker-seasons-api';
import { register as registerGetWatchingWatchedEpisodes } from './get-series-tracker-watched-episodes-api';
import { register as registerTagManagement } from './get-tag-management-api';
import { register as registerUserSettings } from './get-user-settings-api';
import { register as registerHealth } from './health-api';
import { register as registerUserShares } from './user-shares-api';
import { register as registerLogout } from './logout-api';
import { register as registerMarkAllUnwatched } from './mark-all-unwatched-api';
import { register as registerMarkAllWatched } from './mark-all-watched-api';
import { register as registerProxyAi } from './proxy-ai-query-api';
import { register as registerProxyAiAvailable } from './proxy-ai-available-api';
import { register as registerProxyExternalMetadataProviders } from './proxy-external-metadata-providers-api';
import { register as registerProxyExternalMetadataItem } from './proxy-get-external-metadata-item-api';
import { register as registerProxyImage } from './proxy-image-api';
import { register as registerProxyExternalMetadataSearch } from './proxy-external-metadata-search-api';
import { register as registerRandomImages } from './random-images-api';
import { register as registerRefreshExternalRatings } from './refresh-external-ratings-api';
import { register as registerRefreshImages } from './refresh-images-api';
import { register as registerRandomItem } from './random-item-api';
import { register as registerRefreshToken } from './refresh-token-api';
import { register as registerRefreshWatchingSeasons } from './refresh-series-tracker-seasons-api';
import { register as registerSignIn } from './sign-in-api';
import { register as registerSignUp } from './sign-up-api';
import { register as registerSaveUserShare } from './save-user-share-api';
import { register as registerStatistics } from './statistics-api';
import { register as registerTagSuggestions } from './tag-suggestions-api';
import { register as registerExport } from './export-api';
import { register as registerImportCollectionItems } from './import-collection-items-api';
import { register as registerImport } from './import-api';

export const registerAllApis = (app: FastifyInstance): void => {
  registerHealth(app);
  registerSignUp(app);
  registerSignIn(app);
  registerRefreshToken(app);
  registerLogout(app);
  registerCreateAccessToken(app);
  registerAccessTokens(app);
  registerDeleteAccessToken(app);
  registerChangeToken(app);
  registerDeleteUser(app);
  registerGetCollectionItems(app);
  registerCollectionItemsMatched(app);
  registerCollectionItemsSearchSuggestions(app);
  registerCollectionItemsExists(app);
  registerRandomItem(app);
  registerRandomImages(app);
  registerMarkAllWatched(app);
  registerMarkAllUnwatched(app);
  registerMarkAllSeriesWatched(app);
  registerMarkAllSeriesUnwatched(app);
  registerAddWatchedItem(app);
  registerAddWatchingItem(app);
  registerDeleteWatchedItems(app);
  registerDeleteBooksItems(app);
  registerDeleteWatchedItem(app);
  registerDeleteWatchingItems(app);
  registerRefreshExternalRatings(app);
  registerRefreshImages(app);
  registerCreate(app);
  registerModify(app);
  registerDelete(app);
  registerTagManagement(app);
  registerUpdateTagManagement(app);
  registerRenameTagManagement(app);
  registerUserSettings(app);
  registerChangeUserSettings(app);
  registerUserShares(app);
  registerSaveUserShare(app);
  registerDeleteIncomingUserShare(app);
  registerDeleteUserShare(app);
  registerTagSuggestions(app);
  registerGenreSuggestions(app);
  registerStatistics(app);
  registerGetWatchingSeasons(app);
  registerGetWatchingWatchedEpisodes(app);
  registerRefreshWatchingSeasons(app);
  registerChangeWatchingSeasons(app);
  registerChangeWatchingWatchedEpisodes(app);
  registerMarkAllWatchingWatched(app);
  registerDeleteWatchingSeasons(app);
  registerProxyExternalMetadataProviders(app);
  registerProxyExternalMetadataSearch(app);
  registerProxyExternalMetadataItem(app);
  registerProxyImage(app);
  registerProxyAi(app);
  registerProxyAiAvailable(app);
  registerExport(app);
  registerImportCollectionItems(app);
  registerImport(app);
};
