import type { FastifyInstance } from 'fastify';
import { register as registerAccessTokens } from './access-tokens-api';
import { register as registerModify } from './change-api';
import { register as registerChangeTagConfig } from './change-tag-config-api';
import { register as registerChangeToken } from './change-token-api';
import { register as registerChangeUserSettings } from './change-user-settings-api';
import { register as registerCollectionItemsExists } from './collection-items-exists-api';
import { register as registerCollectionItemsMatched } from './collection-items-matched-api';
import { register as registerCollectionItemsSearchSuggestions } from './collection-items-search-suggestions-api';
import { register as registerChangeSeriesTrackerSeasons } from './change-series-tracker-seasons-api';
import { register as registerCreateAccessToken } from './create-access-token-api';
import { register as registerCreate } from './create-api';
import { register as registerDeleteAccessToken } from './delete-access-token-api';
import { register as registerDelete } from './delete-api';
import { register as registerDeleteSeriesTrackerSeasons } from './delete-series-tracker-seasons-api';
import { register as registerDeleteUser } from './delete-user-api';
import { register as registerGenreSuggestions } from './genre-suggestions-api';
import { register as registerGetCollectionItems } from './get-collection-items-api';
import { register as registerGetSeriesTrackerSeasons } from './get-series-tracker-seasons-api';
import { register as registerTagConfig } from './get-tag-config-api';
import { register as registerUserSettings } from './get-user-settings-api';
import { register as registerHealth } from './health-api';
import { register as registerUserShares } from './user-shares-api';
import { register as registerLogout } from './logout-api';
import { register as registerMarkAllUnwatched } from './mark-all-unwatched-api';
import { register as registerMarkAllWatched } from './mark-all-watched-api';
import { register as registerProxyAi } from './proxy-ai-query-api';
import { register as registerProxyAiAvailable } from './proxy-ai-available-api';
import { register as registerProxyOMDbItem } from './proxy-get-omdb-item-api';
import { register as registerProxyImage } from './proxy-image-api';
import { register as registerProxyOMDbSearch } from './proxy-omdb-search-api';
import { register as registerRandomImages } from './random-images-api';
import { register as registerRefreshImages } from './refresh-images-api';
import { register as registerRandomItem } from './random-item-api';
import { register as registerRefreshToken } from './refresh-token-api';
import { register as registerRefreshSeriesTrackerSeasons } from './refresh-series-tracker-seasons-api';
import { register as registerSignIn } from './sign-in-api';
import { register as registerSignUp } from './sign-up-api';
import { register as registerStatistics } from './statistics-api';
import { register as registerTagSuggestions } from './tag-suggestions-api';

export const registerAllApis = (app: FastifyInstance): void => {
  registerHealth(app);
  registerSignUp(app);
  registerSignIn(app);
  registerRefreshToken(app);
  registerLogout(app);
  registerCreateAccessToken(app);
  registerAccessTokens(app);
  registerDeleteAccessToken(app);
  registerChangeToken(app);
  registerDeleteUser(app);
  registerGetCollectionItems(app);
  registerCollectionItemsMatched(app);
  registerCollectionItemsSearchSuggestions(app);
  registerCollectionItemsExists(app);
  registerRandomItem(app);
  registerRandomImages(app);
  registerMarkAllWatched(app);
  registerMarkAllUnwatched(app);
  registerRefreshImages(app);
  registerCreate(app);
  registerModify(app);
  registerDelete(app);
  registerTagConfig(app);
  registerChangeTagConfig(app);
  registerUserSettings(app);
  registerChangeUserSettings(app);
  registerUserShares(app);
  registerTagSuggestions(app);
  registerGenreSuggestions(app);
  registerStatistics(app);
  registerGetSeriesTrackerSeasons(app);
  registerRefreshSeriesTrackerSeasons(app);
  registerChangeSeriesTrackerSeasons(app);
  registerDeleteSeriesTrackerSeasons(app);
  registerProxyOMDbSearch(app);
  registerProxyOMDbItem(app);
  registerProxyImage(app);
  registerProxyAi(app);
  registerProxyAiAvailable(app);
};
