import {
  COMPLETED_TAG,
  FAVORITE_TAG,
  MOVIE_TAG,
  SERIES_TAG,
  VIRTUAL_TAGS,
  WATCH_LATER_TAG,
  WATCHED_TAG,
  WISHLIST_TAG,
} from '@shared/constants/tags-const';

export const INTERNAL_COLLECTION_TAGS = [WATCH_LATER_TAG, WISHLIST_TAG];
export const INTERNAL_TAGS = [
  WATCHED_TAG,
  COMPLETED_TAG,
  FAVORITE_TAG,
  ...INTERNAL_COLLECTION_TAGS,
  MOVIE_TAG,
  SERIES_TAG,
];
export const SUGGESTION_SYSTEM_TAGS = [
  ...VIRTUAL_TAGS,
  WATCHED_TAG,
  COMPLETED_TAG,
  FAVORITE_TAG,
  ...INTERNAL_COLLECTION_TAGS,
  MOVIE_TAG,
  SERIES_TAG,
];
