#!/bin/sh

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

node scripts/fix-eol.js

npm run format:affected
npm run lint:affected
npm run typecheck:affected
npm run typecheck:spec:affected

echo "$FILES" | xargs git add

